- type: playTimeTracker
  id: JobBlueshieldOfficer

- type: playTimeTracker
  id: JobBrigmedic

- type: playTimeTracker
  id: JobDSLeader

- type: playTimeTracker
  id: JobDSOfficer

- type: playTimeTracker
  id: JobDSSpecialist
